<?php
/**
 * Created by PhpStorm.
 * User: yuyu
 * Date: 2017/12/29
 * Time: 下午4:29
 */



    //Auth


    Route::middleware('auth')->group(function () {

        Route::resource('dashboard', 'DashBoardController');

        Route::get('/admin/{admin}/assign','AdminController@assign');
        Route::post('admin/{admin}/assign','AdminController@assign');
        Route::get('admin/{admin}/role','AdminController@role');
        Route::post('admin/{admin}/role','AdminController@role');
        Route::resource('admin', 'AdminController');

        Route::namespace('Generator')->prefix('generator/crud')->group(function (){
           Route::get('','CrudController@show');
           Route::get('model','CrudController@model');
           Route::post('run','CrudController@run');
        });

        /**
        * route for App\Model\Role
        * @author  Generated By Paladin CRUD Generator
        */
        Route::resource('role','RoleController');

        Route::get('/role/{role}/assign','RoleController@assign');
        Route::post('role/{role}/assign','RoleController@assign');

    });


    /**
    * route for App\Model\Permission
    * @author  Generated By Paladin CRUD Generator
    */
    Route::resource('permission','PermissionController');


    /**
    * route for App\Model\Menu
    * @author  Generated By Paladin CRUD Generator
    */
    Route::get('menu/create/{parent?}','MenuController@create');
    Route::get('menu/{menu}/delete','MenuController@destroy');
    Route::resource('menu','MenuController',['except' => ['create','delete']]);

