/**
* route for {{get_class($model)}}
* @author Generated By Paladin CRUD Generator
*/

Route::middleware('auth')
    ->middleware('paladin')
    ->group(function(){
        Route::get('{{$modelName}}/___modelName___/delete','{{$ModelName}}Controller@destroy');;
        Route::resource('{{$modelName}}','{{$ModelName}}Controller',['except'=>['delete']]);
    });
