/**
* route for {{get_class($model)}}
* @author Generated By Paladin CRUD Generator
*/
Route::middleware('auth')
    ->middleware('paladin')
    ->resource('{{$modelName}}','{{$ModelName}}Controller');