<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dashboard', 'DashBoardController');

Route::resource('admin', 'AdminController');
Route::get('/admin/{admin}/assign','AdminController@assign');
Route::post('admin/{admin}/assign','AdminController@assign');

Route::namespace('Generator')->prefix('generator/crud')->group(function (){
   Route::get('','CrudController@show');
   Route::get('model','CrudController@model');
   Route::post('run','CrudController@run');
});

/**
* route for App\Model\Role
* @author  Generated By Paladin CRUD Generator
*/
Route::resource('role','RoleController');

Route::get('/role/{role}/assign','RoleController@assign');
Route::post('role/{role}/assign','RoleController@assign');


/**
* route for App\Model\Permission
* @author  Generated By Paladin CRUD Generator
*/
Route::resource('permission','PermissionController');


/**
* route for App\Model\Menu
* @author  Generated By Paladin CRUD Generator
*/
Route::get('menu/create/{parent?}','MenuController@create');
Route::get('menu/{menu}/delete','MenuController@destroy');
Route::resource('menu','MenuController',['except' => ['create','delete']]);
