<?php
/**
 * Created by PhpStorm.
 * User: yuyu
 * Date: 2017/12/29
 * Time: 下午6:00
 */

namespace Charlestide\Paladin\Providers;

use Charlestide\Paladin\Models\Admin;
use Charlestide\Paladin\Models\Role;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class RouteProvider extends ServiceProvider
{

    protected $namespace = 'Charlestide\Paladin\Controllers';

    protected $middleware = ['paladin'];

    protected $middlewareGroups = [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
    ];

    public function boot()
    {
        parent::boot();

        Route::model('admin',Admin::class);
        Route::model('role',Role::class);
    }

    public function map() {
        Route::middlewareGroup('paladin',$this->middlewareGroups);
        Route::namespace($this->namespace)
            ->middleware('paladin')

            ->group(function () {

                //Auth
                Route::get('login','LoginController@showLoginForm')->name('login');
                Route::post('login','LoginController@login');
                Route::post('logout', 'LoginController@logout')->name('logout');

                //Dashboard
                Route::group(['middleware' => 'auth'],function () {
                    Route::get('dashboard', 'DashBoardController@index');
                });


                Route::match(['get','post'],'/admin/{admin}/assign','AdminController@assign');
//                Route::post('admin/{admin}/assign','AdminController@assign');
                Route::get('admin/{admin}/role','AdminController@role');
                Route::post('admin/{admin}/role','AdminController@role');
                Route::resource('admin', 'AdminController');

                Route::namespace('Generator')->prefix('generator/crud')->group(function (){
                    Route::get('','CrudController@show');
                    Route::get('model','CrudController@model');
                    Route::post('run','CrudController@run');
                });

                /**
                 * route for App\Model\Role
                 * @author  Generated By Paladin CRUD Generator
                 */
                Route::resource('role','RoleController');

                Route::get('/role/{role}/assign','RoleController@assign');
                Route::post('role/{role}/assign','RoleController@assign');

                /**
                 * route for App\Model\Permission
                 * @author  Generated By Paladin CRUD Generator
                 */
                Route::resource('permission','PermissionController');


                /**
                 * route for App\Model\Menu
                 * @author  Generated By Paladin CRUD Generator
                 */
                Route::get('menu/create/{parent?}','MenuController@create');
                Route::get('menu/{menu}/delete','MenuController@destroy');
                Route::resource('menu','MenuController',['except' => ['create','delete']]);
            });
    }

    public function mapCrud() {

    }



}